version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs

  gogs:
    image: gogs/gogs
    # For katacoda: Need to link a configuration file from the host here
    depends_on:
      - db
    # For katacoda: This may be unnecessary, as we hope to avoid access outside of the local docker network
    ports:
      - "8300:3000"
      - "8322:22"

  drone-server:
    image: drone/drone:1
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_RPC_SECRET=verysecret
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
    ports:
      - "8800:80"

  drone-runner:
    image: drone/drone-runner-docker:1
    depends_on:
      - drone-server
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=verysecret
      - DRONE_RUNNER_CAPACITY=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # @todo registry  
  # @todo storedog  